In [5]:
import csv
from math import radians, sin, cos, sqrt, atan2

In [4]:
def convert_value(value):
    try:
        return int(value)
    except ValueError:
        try:
            return float(value)
        except ValueError:
            return value

def Read_Stations(file_path):
    data_dict = {}
    with open(file_path, mode='r', encoding='utf-8') as file:
        csv_reader = csv.DictReader(file)
        for row in csv_reader:
            id_ = int(row.pop('id'))
            cleaned_row = {
                key: convert_value(value) 
                for key, value in row.items()
            }
            data_dict[id_] = cleaned_row
    return data_dict

In [7]:
file_path = r"E:\GitHub\2XC3_Final_Project\london_stations.csv"
station_dict = Read_Stations(file_path)

for id, data in station_dict.items():
    print(f"ID: {id}, Data: {data}")

ID: 1, Data: {'latitude': 51.5028, 'longitude': -0.2801, 'name': 'Acton Town', 'display_name': 'Acton<br />Town', 'zone': 3, 'total_lines': 2, 'rail': 0}
ID: 2, Data: {'latitude': 51.5143, 'longitude': -0.0755, 'name': 'Aldgate', 'display_name': 'NULL', 'zone': 1, 'total_lines': 2, 'rail': 0}
ID: 3, Data: {'latitude': 51.5154, 'longitude': -0.0726, 'name': 'Aldgate East', 'display_name': 'Aldgate<br />East', 'zone': 1, 'total_lines': 2, 'rail': 0}
ID: 4, Data: {'latitude': 51.5107, 'longitude': -0.013, 'name': 'All Saints', 'display_name': 'All<br />Saints', 'zone': 2, 'total_lines': 1, 'rail': 0}
ID: 5, Data: {'latitude': 51.5407, 'longitude': -0.2997, 'name': 'Alperton', 'display_name': 'NULL', 'zone': 4, 'total_lines': 1, 'rail': 0}
ID: 7, Data: {'latitude': 51.5322, 'longitude': -0.1058, 'name': 'Angel', 'display_name': 'NULL', 'zone': 1, 'total_lines': 1, 'rail': 0}
ID: 8, Data: {'latitude': 51.5653, 'longitude': -0.1353, 'name': 'Archway', 'display_name': 'NULL', 'zone': 2.5, 'total_lines': 1, 'rail': 0}
ID: 9, Data: {'latitude': 51.6164, 'longitude': -0.1331, 'name': 'Arnos Grove', 'display_name': 'Arnos<br />Grove', 'zone': 4, 'total_lines': 1, 'rail': 0}
ID: 10, Data: {'latitude': 51.5586, 'longitude': -0.1059, 'name': 'Arsenal', 'display_name': 'NULL', 'zone': 2, 'total_lines': 1, 'rail': 0}
ID: 11, Data: {'latitude': 51.5226, 'longitude': -0.1571, 'name': 'Baker Street', 'display_name': 'Baker<br />Street', 'zone': 1, 'total_lines': 5, 'rail': 0}
ID: 12, Data: {'latitude': 51.4431, 'longitude': -0.1525, 'name': 'Balham', 'display_name': 'NULL', 'zone': 3, 'total_lines': 1, 'rail': 1}
ID: 13, Data: {'latitude': 51.5133, 'longitude': -0.0886, 'name': 'Bank', 'display_name': 'NULL', 'zone': 1, 'total_lines': 4, 'rail': 0}
ID: 14, Data: {'latitude': 51.5204, 'longitude': -0.0979, 'name': 'Barbican', 'display_name': 'NULL', 'zone': 1, 'total_lines': 3, 'rail': 0}
ID: 15, Data: {'latitude': 51.5396, 'longitude': 0.081, 'name': 'Barking', 'display_name': 'NULL', 'zone': 4, 'total_lines': 2, 'rail': 1}
ID: 16, Data: {'latitude': 51.5856, 'longitude': 0.0887, 'name': 'Barkingside', 'display_name': 'NULL', 'zone': 5, 'total_lines': 1, 'rail': 0}
ID: 17, Data: {'latitude': 51.4905, 'longitude': -0.2139, 'name': 'Barons Court', 'display_name': 'Barons<br />Court', 'zone': 2, 'total_lines': 2, 'rail': 0}
ID: 18, Data: {'latitude': 51.5121, 'longitude': -0.1879, 'name': 'Bayswater', 'display_name': 'NULL', 'zone': 1, 'total_lines': 2, 'rail': 0}
ID: 19, Data: {'latitude': 51.5148, 'longitude': 0.0613, 'name': 'Beckton', 'display_name': 'NULL', 'zone': 3, 'total_lines': 1, 'rail': 0}
ID: 20, Data: {'latitude': 51.5087, 'longitude': 0.055, 'name': 'Beckton Park', 'display_name': 'Beckton<br />Park', 'zone': 3, 'total_lines': 1, 'rail': 0}
ID: 21, Data: {'latitude': 51.5403, 'longitude': 0.127, 'name': 'Becontree', 'display_name': 'NULL', 'zone': 5, 'total_lines': 1, 'rail': 0}
ID: 22, Data: {'latitude': 51.5504, 'longitude': -0.1642, 'name': 'Belsize Park', 'display_name': 'Belsize<br />Park', 'zone': 2, 'total_lines': 1, 'rail': 0}
ID: 24, Data: {'latitude': 51.527, 'longitude': -0.0549, 'name': 'Bethnal Green', 'display_name': 'Bethnal<br />Green', 'zone': 2, 'total_lines': 1, 'rail': 0}
ID: 25, Data: {'latitude': 51.512, 'longitude': -0.1031, 'name': 'Blackfriars', 'display_name': 'NULL', 'zone': 1, 'total_lines': 2, 'rail': 0}
ID: 26, Data: {'latitude': 51.5867, 'longitude': -0.0417, 'name': 'Blackhorse Road', 'display_name': 'Blackhorse<br />Road', 'zone': 3, 'total_lines': 1, 'rail': 1}
ID: 27, Data: {'latitude': 51.5079, 'longitude': -0.0066, 'name': 'Blackwall', 'display_name': 'NULL', 'zone': 2, 'total_lines': 1, 'rail': 0}
ID: 28, Data: {'latitude': 51.5142, 'longitude': -0.1494, 'name': 'Bond Street', 'display_name': 'Bond<br />Street', 'zone': 1, 'total_lines': 2, 'rail': 0}
ID: 29, Data: {'latitude': 51.5011, 'longitude': -0.0943, 'name': 'Borough', 'display_name': 'NULL', 'zone': 1, 'total_lines': 1, 'rail': 0}
ID: 30, Data: {'latitude': 51.4956, 'longitude': -0.325, 'name': 'Boston Manor', 'display_name': 'Boston<br />Manor', 'zone': 4, 'total_lines': 1, 'rail': 0}
ID: 31, Data: {'latitude': 51.6071, 'longitude': -0.1243, 'name': 'Bounds Green', 'display_name': 'Bounds<br />Green', 'zone': 3.5, 'total_lines': 1, 'rail': 0}
ID: 32, Data: {'latitude': 51.5273, 'longitude': -0.0208, 'name': 'Bow Church', 'display_name': 'Bow<br />Church', 'zone': 2, 'total_lines': 3, 'rail': 0}
ID: 33, Data: {'latitude': 51.5269, 'longitude': -0.0247, 'name': 'Bow Road', 'display_name': 'Bow<br />Road', 'zone': 2, 'total_lines': 2, 'rail': 0}
ID: 34, Data: {'latitude': 51.5766, 'longitude': -0.2136, 'name': 'Brent Cross', 'display_name': 'Brent<br />Cross', 'zone': 3, 'total_lines': 1, 'rail': 0}
ID: 36, Data: {'latitude': 51.5248, 'longitude': -0.0119, 'name': 'Bromley-By-Bow', 'display_name': 'NULL', 'zone': 2.5, 'total_lines': 2, 'rail': 0}
ID: 38, Data: {'latitude': 51.6028, 'longitude': -0.2641, 'name': 'Burnt Oak', 'display_name': 'Burnt<br />Oak', 'zone': 4, 'total_lines': 1, 'rail': 0}
ID: 39, Data: {'latitude': 51.5481, 'longitude': -0.1188, 'name': 'Caledonian Road', 'display_name': 'Caledonian<br />Road', 'zone': 2, 'total_lines': 1, 'rail': 0}
ID: 40, Data: {'latitude': 51.5392, 'longitude': -0.1426, 'name': 'Camden Town', 'display_name': 'Camden<br />Town', 'zone': 2, 'total_lines': 1, 'rail': 0}
ID: 42, Data: {'latitude': 51.5051, 'longitude': -0.0209, 'name': 'Canary Wharf', 'display_name': 'Canary<br />Wharf', 'zone': 2, 'total_lines': 2, 'rail': 0}
ID: 44, Data: {'latitude': 51.5113, 'longitude': -0.0904, 'name': 'Cannon Street', 'display_name': 'Cannon<br />Street', 'zone': 1, 'total_lines': 2, 'rail': 0}
ID: 45, Data: {'latitude': 51.6078, 'longitude': -0.2947, 'name': 'Canons Park', 'display_name': 'Canons<br />Park', 'zone': 5, 'total_lines': 1, 'rail': 0}
ID: 47, Data: {'latitude': 51.5441, 'longitude': -0.1538, 'name': 'Chalk Farm', 'display_name': 'Chalk<br />Farm', 'zone': 2, 'total_lines': 1, 'rail': 0}
ID: 48, Data: {'latitude': 51.5185, 'longitude': -0.1111, 'name': 'Chancery Lane', 'display_name': 'Chancery<br />Lane', 'zone': 1, 'total_lines': 1, 'rail': 0}
ID: 49, Data: {'latitude': 51.508, 'longitude': -0.1247, 'name': 'Charing Cross', 'display_name': 'Charing<br />Cross', 'zone': 1, 'total_lines': 2, 'rail': 1}
ID: 51, Data: {'latitude': 51.6177, 'longitude': 0.0755, 'name': 'Chigwell', 'display_name': 'NULL', 'zone': 5, 'total_lines': 1, 'rail': 0}
ID: 52, Data: {'latitude': 51.4946, 'longitude': -0.2678, 'name': 'Chiswick Park', 'display_name': 'Chiswick<br />Park', 'zone': 3, 'total_lines': 1, 'rail': 0}
ID: 54, Data: {'latitude': 51.4618, 'longitude': -0.1384, 'name': 'Clapham Common', 'display_name': 'Clapham<br />Common', 'zone': 2, 'total_lines': 1, 'rail': 0}
ID: 55, Data: {'latitude': 51.4649, 'longitude': -0.1299, 'name': 'Clapham North', 'display_name': 'Clapham<br />North', 'zone': 2, 'total_lines': 1, 'rail': 0}
ID: 56, Data: {'latitude': 51.4527, 'longitude': -0.148, 'name': 'Clapham South', 'display_name': 'Clapham<br />South', 'zone': 2.5, 'total_lines': 1, 'rail': 0}
ID: 58, Data: {'latitude': 51.5955, 'longitude': -0.2502, 'name': 'Colindale', 'display_name': 'NULL', 'zone': 4, 'total_lines': 1, 'rail': 0}
ID: 59, Data: {'latitude': 51.418, 'longitude': -0.1778, 'name': 'Colliers Wood', 'display_name': 'Colliers<br />Wood', 'zone': 3, 'total_lines': 1, 'rail': 0}
ID: 60, Data: {'latitude': 51.5129, 'longitude': -0.1243, 'name': 'Covent Garden', 'display_name': 'Covent<br />Garden', 'zone': 1, 'total_lines': 1, 'rail': 0}
ID: 61, Data: {'latitude': 51.4957, 'longitude': -0.0144, 'name': 'Crossharbour & London Arena', 'display_name': 'Crossharbour &<br />London Arena', 'zone': 2, 'total_lines': 1, 'rail': 0}
ID: 63, Data: {'latitude': 51.5095, 'longitude': 0.0276, 'name': 'Custom House', 'display_name': 'Custom<br />House', 'zone': 3, 'total_lines': 1, 'rail': 0}
ID: 65, Data: {'latitude': 51.5085, 'longitude': 0.064, 'name': 'Cyprus', 'display_name': 'NULL', 'zone': 3, 'total_lines': 1, 'rail': 0}
ID: 66, Data: {'latitude': 51.5443, 'longitude': 0.1655, 'name': 'Dagenham East', 'display_name': 'Dagenham<br />East', 'zone': 5, 'total_lines': 1, 'rail': 0}
ID: 67, Data: {'latitude': 51.5417, 'longitude': 0.1469, 'name': 'Dagenham Heathway', 'display_name': 'Dagenham<br />Heathway', 'zone': 5, 'total_lines': 1, 'rail': 0}
ID: 70, Data: {'latitude': 51.5223, 'longitude': -0.0173, 'name': 'Devons Road', 'display_name': 'Devons<br />Road', 'zone': 2, 'total_lines': 1, 'rail': 0}
ID: 71, Data: {'latitude': 51.552, 'longitude': -0.2387, 'name': 'Dollis Hill', 'display_name': 'Dollis<br />Hill', 'zone': 3, 'total_lines': 1, 'rail': 0}
ID: 72, Data: {'latitude': 51.5152, 'longitude': -0.3017, 'name': 'Ealing Broadway', 'display_name': 'Ealing<br />Broadway', 'zone': 3, 'total_lines': 2, 'rail': 1}
ID: 73, Data: {'latitude': 51.5101, 'longitude': -0.2882, 'name': 'Ealing Common', 'display_name': 'Ealing<br />Common', 'zone': 3, 'total_lines': 2, 'rail': 0}
ID: 74, Data: {'latitude': 51.492, 'longitude': -0.1973, 'name': "Earl's Court", 'display_name': "Earl's<br />Court", 'zone': 1.5, 'total_lines': 2, 'rail': 0}
ID: 75, Data: {'latitude': 51.5765, 'longitude': -0.397, 'name': 'Eastcote', 'display_name': 'NULL', 'zone': 5, 'total_lines': 2, 'rail': 0}
ID: 76, Data: {'latitude': 51.5168, 'longitude': -0.2474, 'name': 'East Acton', 'display_name': 'East<br />Acton', 'zone': 2, 'total_lines': 1, 'rail': 0}
ID: 77, Data: {'latitude': 51.5874, 'longitude': -0.165, 'name': 'East Finchley', 'display_name': 'East<br />Finchley', 'zone': 3, 'total_lines': 1, 'rail': 0}
ID: 78, Data: {'latitude': 51.5394, 'longitude': 0.0518, 'name': 'East Ham', 'display_name': 'East<br />Ham', 'zone': 3.5, 'total_lines': 2, 'rail': 0}
ID: 79, Data: {'latitude': 51.5093, 'longitude': -0.0021, 'name': 'East India', 'display_name': 'East<br />India', 'zone': 2.5, 'total_lines': 1, 'rail': 0}
ID: 80, Data: {'latitude': 51.4586, 'longitude': -0.2112, 'name': 'East Putney', 'display_name': 'East<br />Putney', 'zone': 2.5, 'total_lines': 1, 'rail': 0}
ID: 81, Data: {'latitude': 51.6137, 'longitude': -0.275, 'name': 'Edgware', 'display_name': 'NULL', 'zone': 5, 'total_lines': 1, 'rail': 0}
ID: 82, Data: {'latitude': 51.5199, 'longitude': -0.1679, 'name': 'Edgware Road (B)', 'display_name': 'Edgware<br />Road', 'zone': 1, 'total_lines': 1, 'rail': 0}
ID: 83, Data: {'latitude': 51.5203, 'longitude': -0.17, 'name': 'Edgware Road (C)', 'display_name': 'Edgware<br />Road', 'zone': 1, 'total_lines': 3, 'rail': 0}
ID: 84, Data: {'latitude': 51.4943, 'longitude': -0.1001, 'name': 'Elephant & Castle', 'display_name': 'Elephant &<br />Castle', 'zone': 1.5, 'total_lines': 2, 'rail': 1}
ID: 85, Data: {'latitude': 51.5496, 'longitude': 0.1977, 'name': 'Elm Park', 'display_name': 'Elm<br />Park', 'zone': 6, 'total_lines': 1, 'rail': 0}
ID: 87, Data: {'latitude': 51.5074, 'longitude': -0.1223, 'name': 'Embankment', 'display_name': 'NULL', 'zone': 1, 'total_lines': 4, 'rail': 0}
ID: 89, Data: {'latitude': 51.5282, 'longitude': -0.1337, 'name': 'Euston', 'display_name': 'NULL', 'zone': 1, 'total_lines': 2, 'rail': 1}
ID: 90, Data: {'latitude': 51.526, 'longitude': -0.1359, 'name': 'Euston Square', 'display_name': 'Euston<br />Square', 'zone': 1, 'total_lines': 3, 'rail': 0}
ID: 91, Data: {'latitude': 51.596, 'longitude': 0.0912, 'name': 'Fairlop', 'display_name': 'NULL', 'zone': 5, 'total_lines': 1, 'rail': 0}
ID: 92, Data: {'latitude': 51.5203, 'longitude': -0.1053, 'name': 'Farringdon', 'display_name': 'NULL', 'zone': 1, 'total_lines': 3, 'rail': 1}
ID: 93, Data: {'latitude': 51.6012, 'longitude': -0.1932, 'name': 'Finchley Central', 'display_name': 'Finchley<br />Central', 'zone': 4, 'total_lines': 1, 'rail': 0}
ID: 94, Data: {'latitude': 51.5472, 'longitude': -0.1803, 'name': 'Finchley Road', 'display_name': 'Finchley<br />Road', 'zone': 2, 'total_lines': 2, 'rail': 0}
ID: 95, Data: {'latitude': 51.5642, 'longitude': -0.1065, 'name': 'Finsbury Park', 'display_name': 'Finsbury<br />Park', 'zone': 2, 'total_lines': 1, 'rail': 1}
ID: 96, Data: {'latitude': 51.4804, 'longitude': -0.195, 'name': 'Fulham Broadway', 'display_name': 'Fulham<br />Broadway', 'zone': 2, 'total_lines': 1, 'rail': 0}
ID: 97, Data: {'latitude': 51.5096, 'longitude': 0.0716, 'name': 'Gallions Reach', 'display_name': 'Gallions<br />Reach', 'zone': 3, 'total_lines': 1, 'rail': 0}
ID: 98, Data: {'latitude': 51.5765, 'longitude': 0.0663, 'name': 'Gants Hill', 'display_name': 'Gants<br />Hill', 'zone': 4, 'total_lines': 1, 'rail': 0}
ID: 99, Data: {'latitude': 51.4945, 'longitude': -0.1829, 'name': 'Gloucester Road', 'display_name': 'Gloucester<br />Road', 'zone': 1, 'total_lines': 3, 'rail': 0}
ID: 100, Data: {'latitude': 51.5724, 'longitude': -0.1941, 'name': 'Golders Green', 'display_name': 'Golders<br />Green', 'zone': 3, 'total_lines': 1, 'rail': 0}
ID: 101, Data: {'latitude': 51.5018, 'longitude': -0.2267, 'name': 'Goldhawk Road', 'display_name': 'Goldhawk<br />Road', 'zone': 2, 'total_lines': 1, 'rail': 0}
ID: 102, Data: {'latitude': 51.5205, 'longitude': -0.1347, 'name': 'Goodge Street', 'display_name': 'Goodge<br />Street', 'zone': 1, 'total_lines': 1, 'rail': 0}
ID: 103, Data: {'latitude': 51.6132, 'longitude': 0.0923, 'name': 'Grange Hill', 'display_name': 'Grange<br />Hill', 'zone': 5, 'total_lines': 1, 'rail': 0}
ID: 104, Data: {'latitude': 51.5238, 'longitude': -0.1439, 'name': 'Great Portland Street', 'display_name': 'Great<br />Portland<br />Street', 'zone': 1, 'total_lines': 3, 'rail': 0}
ID: 105, Data: {'latitude': 51.5423, 'longitude': -0.3456, 'name': 'Greenford', 'display_name': 'NULL', 'zone': 4, 'total_lines': 1, 'rail': 1}
ID: 107, Data: {'latitude': 51.5067, 'longitude': -0.1428, 'name': 'Green Park', 'display_name': 'Green<br />Park', 'zone': 1, 'total_lines': 3, 'rail': 0}
ID: 108, Data: {'latitude': 51.4915, 'longitude': -0.2754, 'name': 'Gunnersbury', 'display_name': 'NULL', 'zone': 3, 'total_lines': 1, 'rail': 0}
ID: 109, Data: {'latitude': 51.603, 'longitude': 0.0933, 'name': 'Hainault', 'display_name': 'NULL', 'zone': 5, 'total_lines': 1, 'rail': 0}
ID: 110, Data: {'latitude': 51.4936, 'longitude': -0.2251, 'name': 'Hammersmith', 'display_name': 'NULL', 'zone': 2, 'total_lines': 3, 'rail': 0}
ID: 111, Data: {'latitude': 51.5568, 'longitude': -0.178, 'name': 'Hampstead', 'display_name': 'NULL', 'zone': 2.5, 'total_lines': 1, 'rail': 0}
ID: 112, Data: {'latitude': 51.5302, 'longitude': -0.2933, 'name': 'Hanger Lane', 'display_name': 'Hanger<br />Lane', 'zone': 3, 'total_lines': 1, 'rail': 0}
ID: 113, Data: {'latitude': 51.5362, 'longitude': -0.2575, 'name': 'Harlesden', 'display_name': 'NULL', 'zone': 3, 'total_lines': 1, 'rail': 0}
ID: 114, Data: {'latitude': 51.5925, 'longitude': -0.3351, 'name': 'Harrow & Wealdston', 'display_name': 'Harrow &<br />Wealdston', 'zone': 5, 'total_lines': 1, 'rail': 1}
ID: 115, Data: {'latitude': 51.5793, 'longitude': -0.3366, 'name': 'Harrow-on-the-Hill', 'display_name': 'Harrow-<br />on-the-Hill', 'zone': 5, 'total_lines': 1, 'rail': 1}
ID: 116, Data: {'latitude': 51.4669, 'longitude': -0.4227, 'name': 'Hatton Cross', 'display_name': 'Hatton<br />Cross', 'zone': 5.5, 'total_lines': 1, 'rail': 0}
ID: 117, Data: {'latitude': 51.4713, 'longitude': -0.4524, 'name': 'Heathrow Terminals 1, 2 & 3', 'display_name': 'Heathrow<br />Terminals<br />1, 2 & 3', 'zone': 6, 'total_lines': 1, 'rail': 0}
ID: 118, Data: {'latitude': 51.4598, 'longitude': -0.4476, 'name': 'Heathrow Terminal 4', 'display_name': 'Heathrow<br />Terminal 4', 'zone': 6, 'total_lines': 1, 'rail': 0}
ID: 119, Data: {'latitude': 51.5829, 'longitude': -0.2259, 'name': 'Hendon Central', 'display_name': 'Hendon<br />Central', 'zone': 3.5, 'total_lines': 1, 'rail': 0}
ID: 120, Data: {'latitude': 51.5033, 'longitude': -0.0215, 'name': 'Heron Quays', 'display_name': 'Heron<br />Quays', 'zone': 2, 'total_lines': 1, 'rail': 0}
ID: 122, Data: {'latitude': 51.5009, 'longitude': -0.1925, 'name': 'High Street Kensington', 'display_name': 'High<br />Street<br />Kensington', 'zone': 1, 'total_lines': 2, 'rail': 0}
ID: 123, Data: {'latitude': 51.546, 'longitude': -0.104, 'name': 'Highbury & Islington', 'display_name': 'Highbury &<br />Islington', 'zone': 2, 'total_lines': 1, 'rail': 1}
ID: 124, Data: {'latitude': 51.5777, 'longitude': -0.1458, 'name': 'Highgate', 'display_name': 'NULL', 'zone': 3, 'total_lines': 1, 'rail': 0}
ID: 125, Data: {'latitude': 51.5538, 'longitude': -0.4499, 'name': 'Hillingdon', 'display_name': 'NULL', 'zone': 6, 'total_lines': 2, 'rail': 0}
ID: 126, Data: {'latitude': 51.5174, 'longitude': -0.12, 'name': 'Holborn', 'display_name': 'NULL', 'zone': 1, 'total_lines': 2, 'rail': 0}
ID: 127, Data: {'latitude': 51.5075, 'longitude': -0.206, 'name': 'Holland Park', 'display_name': 'Holland<br />Park', 'zone': 2, 'total_lines': 1, 'rail': 0}
ID: 128, Data: {'latitude': 51.5526, 'longitude': -0.1132, 'name': 'Holloway Road', 'display_name': 'Holloway<br />Road', 'zone': 2, 'total_lines': 1, 'rail': 0}
ID: 129, Data: {'latitude': 51.5539, 'longitude': 0.2184, 'name': 'Hornchurch', 'display_name': 'NULL', 'zone': 6, 'total_lines': 1, 'rail': 0}
ID: 130, Data: {'latitude': 51.4713, 'longitude': -0.3665, 'name': 'Hounslow Central', 'display_name': 'Hounslow<br />Central', 'zone': 4, 'total_lines': 1, 'rail': 0}
ID: 131, Data: {'latitude': 51.4733, 'longitude': -0.3564, 'name': 'Hounslow East', 'display_name': 'Hounslow<br />East', 'zone': 4, 'total_lines': 1, 'rail': 0}
ID: 132, Data: {'latitude': 51.4734, 'longitude': -0.3855, 'name': 'Hounslow West', 'display_name': 'Hounslow<br />West', 'zone': 5, 'total_lines': 1, 'rail': 0}
ID: 133, Data: {'latitude': 51.5027, 'longitude': -0.1527, 'name': 'Hyde Park Corner', 'display_name': 'Hyde<br />Park<br />Corner', 'zone': 1, 'total_lines': 1, 'rail': 0}
ID: 134, Data: {'latitude': 51.5619, 'longitude': -0.4421, 'name': 'Ickenham', 'display_name': 'NULL', 'zone': 6, 'total_lines': 2, 'rail': 0}
ID: 135, Data: {'latitude': 51.4871, 'longitude': -0.0101, 'name': 'Island Gardens', 'display_name': 'Island<br />Gardens', 'zone': 2, 'total_lines': 1, 'rail': 0}
ID: 136, Data: {'latitude': 51.4884, 'longitude': -0.1053, 'name': 'Kennington', 'display_name': 'NULL', 'zone': 2, 'total_lines': 1, 'rail': 0}
ID: 137, Data: {'latitude': 51.5304, 'longitude': -0.225, 'name': 'Kensal Green', 'display_name': 'Kensal<br />Green', 'zone': 2, 'total_lines': 1, 'rail': 0}
ID: 138, Data: {'latitude': 51.4983, 'longitude': -0.2106, 'name': 'Kensington (Olympia)', 'display_name': 'Kensington<br />(Olympia)', 'zone': 2, 'total_lines': 1, 'rail': 1}
ID: 139, Data: {'latitude': 51.5507, 'longitude': -0.1402, 'name': 'Kentish Town', 'display_name': 'Kentish<br />Town', 'zone': 2, 'total_lines': 1, 'rail': 1}
ID: 140, Data: {'latitude': 51.5816, 'longitude': -0.3162, 'name': 'Kenton', 'display_name': 'NULL', 'zone': 4, 'total_lines': 1, 'rail': 0}
ID: 141, Data: {'latitude': 51.477, 'longitude': -0.285, 'name': 'Kew Gardens', 'display_name': 'Kew<br />Gardens', 'zone': 3.5, 'total_lines': 1, 'rail': 0}
ID: 142, Data: {'latitude': 51.5471, 'longitude': -0.2047, 'name': 'Kilburn', 'display_name': 'NULL', 'zone': 2, 'total_lines': 1, 'rail': 0}
ID: 143, Data: {'latitude': 51.5351, 'longitude': -0.1939, 'name': 'Kilburn Park', 'display_name': 'Kilburn<br />Park', 'zone': 2, 'total_lines': 1, 'rail': 0}
ID: 144, Data: {'latitude': 51.5846, 'longitude': -0.2786, 'name': 'Kingsbury', 'display_name': 'NULL', 'zone': 4, 'total_lines': 1, 'rail': 0}
ID: 145, Data: {'latitude': 51.5308, 'longitude': -0.1238, 'name': "King's Cross St. Pancras", 'display_name': "King's Cross<br />St. Pancras", 'zone': 1, 'total_lines': 6, 'rail': 1}
ID: 146, Data: {'latitude': 51.5015, 'longitude': -0.1607, 'name': 'Knightsbridge', 'display_name': 'NULL', 'zone': 1, 'total_lines': 1, 'rail': 0}

In [ ]:
def Distance(lat1, lon1, lat2, lon2):
    R = 6371.0
    lat1, lon1, lat2, lon2 = map(radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
    c = 2 * atan2(sqrt(a), sqrt(1-a))
    return R * c

In [17]:
distance_dict = {}

csv_path = r"E:\GitHub\2XC3_Final_Project\london_connections.csv"
with open(csv_path, mode='r') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        station1 = int(row['station1'])
        station2 = int(row['station2'])
        line = int(row['line'])
        time = int(row['time'])

        st1_info = station_dict.get(station1)
        st2_info = station_dict.get(station2)

        if st1_info and st2_info:
            distance = Distance(
                st1_info['latitude'], st1_info['longitude'],
                st2_info['latitude'], st2_info['longitude']
            )
            
            rounded_distance = round(distance, 4)
            distance_dict[rounded_distance] = (station1, station2, line, time)

In [18]:
for dist, data in sorted(distance_dict.items()):
    print(f"{dist} km: {data}")

0.179 km: (49, 87, 9, 1)
0.2044 km: (42, 120, 13, 2)
0.2153 km: (42, 292, 13, 2)
0.2217 km: (201, 292, 13, 2)
0.2685 km: (44, 161, 4, 1)
0.2891 km: (44, 166, 4, 2)
0.3175 km: (60, 151, 10, 1)
0.3334 km: (120, 238, 13, 2)
0.3482 km: (27, 79, 13, 2)
0.3497 km: (41, 216, 5, 1)
0.4153 km: (11, 163, 1, 1)
0.4158 km: (63, 203, 13, 2)
0.4322 km: (216, 276, 5, 1)
0.4359 km: (49, 151, 9, 2)
0.4403 km: (82, 163, 1, 2)
0.4449 km: (156, 167, 8, 2)
0.445 km: (101, 227, 6, 1)
0.447 km: (4, 201, 13, 2)
0.4539 km: (151, 197, 10, 2)
0.4576 km: (86, 152, 13, 2)
0.46 km: (135, 171, 13, 2)
0.4905 km: (64, 135, 13, 2)
0.5061 km: (2, 263, 3, 4)
0.5071 km: (89, 277, 11, 1)
0.5121 km: (14, 92, 8, 1)
0.5128 km: (17, 293, 4, 2)
0.5132 km: (102, 259, 9, 1)
0.5162 km: (176, 234, 10, 1)
0.5237 km: (284, 292, 13, 2)
0.5326 km: (102, 277, 9, 2)
0.5366 km: (148, 279, 1, 1)
0.54 km: (65, 97, 13, 2)
0.5514 km: (74, 287, 4, 2)
0.5539 km: (28, 192, 2, 1)
0.5696 km: (133, 146, 10, 2)
0.5805 km: (147, 150, 6, 1)
0.5822 km: (60, 126, 10, 1)
0.5882 km: (248, 285, 4, 2)
0.5892 km: (20, 217, 13, 2)
0.5893 km: (13, 167, 9, 3)
0.5981 km: (69, 86, 13, 2)
0.6051 km: (90, 104, 8, 2)
0.6064 km: (32, 70, 13, 2)
0.6093 km: (242, 265, 4, 1)
0.6106 km: (2, 156, 8, 2)
0.6116 km: (61, 171, 13, 2)
0.612 km: (151, 259, 9, 1)
0.618 km: (40, 170, 9, 1)
0.6191 km: (13, 250, 2, 2)
0.6233 km: (20, 65, 13, 2)
0.6241 km: (10, 95, 10, 2)
0.6278 km: (48, 126, 2, 1)
0.6287 km: (33, 164, 6, 1)
0.6296 km: (64, 106, 13, 2)
0.6301 km: (25, 161, 4, 1)
0.6316 km: (99, 236, 10, 1)
0.6324 km: (94, 254, 7, 2)
0.6327 km: (39, 128, 10, 2)
0.6369 km: (220, 222, 10, 2)
0.6394 km: (186, 208, 2, 2)
0.6401 km: (28, 162, 2, 1)
0.6442 km: (61, 238, 13, 2)
0.6505 km: (69, 106, 13, 2)
0.6531 km: (74, 293, 4, 1)
0.659 km: (63, 219, 13, 2)
0.6636 km: (13, 156, 2, 2)
0.6642 km: (198, 272, 11, 1)
0.6646 km: (83, 193, 6, 4)
0.6739 km: (14, 167, 8, 2)
0.6744 km: (201, 284, 13, 2)
0.6774 km: (127, 186, 2, 2)
0.679 km: (18, 186, 4, 2)
0.6804 km: (166, 263, 4, 2)
0.6814 km: (3, 263, 4, 2)
0.6823 km: (54, 55, 9, 2)
0.6873 km: (49, 197, 1, 2)
0.6878 km: (107, 197, 10, 1)
0.6931 km: (126, 223, 10, 2)
0.6947 km: (139, 264, 9, 2)
0.6965 km: (87, 279, 9, 2)
0.698 km: (209, 242, 4, 2)
0.7009 km: (87, 255, 4, 2)
0.7071 km: (96, 195, 4, 2)
0.7119 km: (29, 157, 9, 2)
0.713 km: (94, 290, 7, 1)
0.7223 km: (3, 156, 6, 4)
0.7259 km: (82, 193, 1, 3)
0.7319 km: (11, 212, 1, 2)
0.7341 km: (130, 131, 10, 2)
0.7346 km: (159, 278, 1, 1)
0.7409 km: (27, 201, 13, 2)
0.7433 km: (87, 285, 4, 2)
0.7434 km: (89, 145, 11, 2)
0.7455 km: (192, 259, 2, 2)
0.7483 km: (84, 136, 9, 2)
0.7507 km: (110, 209, 4, 2)
0.7515 km: (89, 170, 9, 2)
0.7552 km: (143, 206, 1, 2)
0.7564 km: (96, 287, 4, 1)
0.7588 km: (228, 295, 5, 2)
0.7677 km: (126, 259, 2, 2)
0.7678 km: (25, 255, 4, 2)
0.7813 km: (113, 298, 1, 2)
0.7872 km: (147, 283, 6, 2)
0.7918 km: (91, 109, 2, 2)
0.8169 km: (107, 133, 10, 2)
0.8209 km: (279, 285, 7, 2)
0.823 km: (225, 276, 5, 1)
0.8236 km: (73, 182, 10, 3)
0.8366 km: (10, 128, 10, 1)
0.8385 km: (71, 172, 7, 2)
0.8397 km: (248, 273, 4, 2)
0.8479 km: (149, 208, 2, 1)
0.8486 km: (17, 110, 10, 2)
0.8529 km: (200, 289, 6, 2)
0.8561 km: (29, 84, 9, 1)
0.8609 km: (167, 188, 9, 1)
0.8643 km: (30, 176, 10, 2)
0.8683 km: (145, 223, 10, 2)
0.8952 km: (221, 239, 2, 1)
0.8981 km: (136, 191, 9, 2)
0.8984 km: (203, 217, 13, 2)
0.9056 km: (3, 295, 6, 2)
0.9086 km: (52, 265, 4, 2)
0.9131 km: (32, 204, 13, 2)
0.9135 km: (13, 157, 9, 2)
0.9158 km: (33, 36, 6, 2)
0.9178 km: (19, 97, 13, 2)
0.9185 km: (101, 110, 6, 2)
0.9222 km: (266, 303, 10, 2)
0.9229 km: (11, 104, 8, 3)
0.9258 km: (43, 219, 13, 2)
0.9273 km: (107, 192, 11, 2)
0.9284 km: (12, 257, 9, 1)
0.9287 km: (225, 295, 5, 2)
0.932 km: (43, 79, 13, 2)
0.9332 km: (18, 193, 4, 2)
0.9333 km: (218, 283, 6, 2)
0.9351 km: (23, 41, 7, 2)
0.9355 km: (229, 273, 4, 2)
0.9359 km: (131, 190, 10, 2)
0.9363 km: (127, 226, 2, 1)
0.9453 km: (249, 254, 7, 1)
0.947 km: (40, 47, 9, 2)
0.9508 km: (28, 107, 7, 2)
0.9516 km: (55, 245, 9, 1)
0.9525 km: (288, 302, 9, 1)
0.9527 km: (84, 148, 1, 3)
0.9531 km: (193, 218, 6, 1)
0.9566 km: (195, 205, 4, 3)
0.9672 km: (8, 264, 9, 2)
0.9737 km: (99, 122, 3, 4)
0.9753 km: (142, 290, 7, 2)
0.983 km: (93, 288, 9, 2)
0.9865 km: (1, 73, 10, 2)
0.9888 km: (122, 186, 4, 3)
0.9927 km: (90, 145, 8, 2)
0.9985 km: (192, 212, 1, 2)
1.0039 km: (22, 47, 9, 2)
1.0042 km: (164, 244, 6, 2)
1.0196 km: (59, 240, 9, 2)
1.0273 km: (244, 295, 6, 3)
1.035 km: (74, 99, 10, 2)
1.0439 km: (74, 122, 4, 3)
1.0488 km: (48, 250, 2, 2)
1.0498 km: (125, 134, 10, 2)
1.0531 km: (204, 247, 13, 2)
1.0572 km: (193, 278, 1, 2)
1.0737 km: (95, 160, 10, 2)
1.0753 km: (11, 28, 7, 2)
1.0793 km: (80, 205, 4, 2)
1.0929 km: (72, 73, 4, 4)
1.0997 km: (192, 277, 11, 2)
1.1014 km: (34, 119, 9, 2)
1.1033 km: (182, 194, 10, 2)
1.107 km: (150, 227, 6, 2)
1.1121 km: (12, 56, 9, 2)
1.1125 km: (257, 258, 9, 2)
1.115 km: (16, 173, 2, 2)
1.1194 km: (198, 273, 11, 3)
1.1323 km: (75, 222, 10, 2)
1.1363 km: (103, 109, 2, 3)
1.1369 km: (155, 225, 13, 2)
1.1418 km: (107, 273, 11, 2)
1.1458 km: (76, 181, 2, 2)
1.1542 km: (115, 291, 8, 2)
1.1549 km: (211, 275, 2, 2)
1.1569 km: (74, 138, 4, 2)
1.1579 km: (267, 268, 4, 3)
1.1613 km: (17, 74, 10, 3)
1.1693 km: (16, 91, 2, 2)
1.1849 km: (142, 297, 7, 2)
1.1866 km: (144, 207, 7, 2)
1.1903 km: (22, 111, 9, 2)
1.1915 km: (149, 162, 2, 3)
1.1987 km: (129, 268, 4, 2)
1.1994 km: (9, 31, 10, 3)
1.2109 km: (54, 56, 9, 2)
1.2125 km: (229, 236, 4, 2)
1.2191 km: (35, 245, 11, 2)
1.2245 km: (146, 236, 10, 3)
1.2293 km: (71, 297, 7, 2)
1.2342 km: (26, 260, 11, 2)
1.2358 km: (185, 281, 1, 2)
1.2475 km: (52, 1, 4, 2)
1.2548 km: (7, 145, 9, 2)
1.256 km: (59, 258, 9, 2)
1.2572 km: (38, 58, 9, 2)
1.2598 km: (200, 270, 6, 2)
1.2616 km: (115, 178, 8, 2)
1.2617 km: (224, 260, 11, 3)
1.2633 km: (51, 103, 2, 2)
1.2723 km: (225, 262, 13, 2)
1.2724 km: (191, 245, 9, 3)
1.2787 km: (230, 241, 2, 2)
1.286 km: (36, 289, 6, 2)
1.2895 km: (40, 139, 9, 2)
1.2973 km: (78, 270, 6, 2)
1.31 km: (57, 187, 10, 4)
1.3112 km: (215, 301, 2, 3)
1.3184 km: (66, 67, 4, 4)
1.3213 km: (117, 118, 10, 5)
1.3237 km: (4, 70, 13, 2)
1.3351 km: (210, 291, 8, 3)
1.3365 km: (130, 132, 10, 2)
1.3366 km: (231, 300, 4, 3)
1.3609 km: (107, 285, 7, 3)
1.3693 km: (40, 89, 9, 3)
1.3716 km: (235, 251, 10, 2)
1.3825 km: (157, 233, 7, 2)
1.385 km: (21, 67, 4, 3)
1.3959 km: (140, 237, 1, 2)
1.4059 km: (45, 243, 7, 2)
1.4144 km: (93, 165, 9, 3)
1.4162 km: (15, 269, 4, 2)
1.4262 km: (34, 100, 9, 3)
1.4267 km: (38, 81, 9, 3)
1.4381 km: (7, 188, 9, 3)
1.4394 km: (261, 302, 9, 3)
1.4445 km: (98, 211, 2, 2)
1.4495 km: (202, 282, 8, 3)
1.4632 km: (137, 206, 1, 3)
1.4684 km: (31, 303, 10, 2)
1.4726 km: (72, 286, 2, 3)
1.4815 km: (169, 240, 9, 4)
1.4879 km: (108, 265, 4, 3)
1.502 km: (80, 231, 4, 2)
1.509 km: (85, 129, 4, 2)
1.5188 km: (299, 300, 4, 3)
1.5193 km: (24, 164, 2, 2)
1.5233 km: (184, 199, 8, 3)
1.5338 km: (113, 246, 1, 2)
1.5427 km: (245, 272, 11, 3)
1.5581 km: (8, 124, 9, 3)
1.5638 km: (5, 252, 10, 2)
1.5671 km: (43, 289, 7, 3)
1.5685 km: (179, 180, 8, 2)
1.5865 km: (247, 289, 7, 3)
1.5881 km: (26, 274, 11, 2)
1.596 km: (137, 298, 1, 3)
1.5979 km: (181, 286, 2, 2)
1.6051 km: (153, 154, 2, 3)
1.6068 km: (43, 183, 7, 3)
1.6073 km: (251, 252, 10, 3)
1.6247 km: (45, 207, 7, 2)
1.6339 km: (98, 173, 2, 3)
1.6663 km: (154, 230, 2, 2)
1.6677 km: (246, 281, 1, 3)
1.6697 km: (153, 247, 2, 2)
1.6738 km: (105, 196, 2, 2)
1.7098 km: (77, 124, 9, 2)
1.7115 km: (76, 296, 2, 3)
1.7309 km: (37, 158, 2, 3)
1.7311 km: (105, 177, 2, 2)
1.7324 km: (187, 232, 10, 3)
1.7415 km: (178, 202, 8, 2)
1.744 km: (108, 141, 4, 3)
1.7475 km: (154, 275, 2, 2)
1.7613 km: (241, 301, 2, 2)
1.7685 km: (23, 157, 7, 3)
1.7741 km: (75, 210, 10, 2)
1.7816 km: (114, 140, 1, 2)
1.7818 km: (21, 269, 4, 2)
1.7824 km: (11, 249, 7, 4)
1.7874 km: (210, 235, 10, 3)
1.7906 km: (134, 220, 10, 3)
1.7911 km: (42, 183, 7, 3)
1.7918 km: (9, 232, 10, 3)
1.8013 km: (136, 279, 9, 3)
1.8668 km: (5, 194, 10, 3)
1.8853 km: (1, 234, 10, 4)
1.8907 km: (115, 184, 8, 3)
1.8961 km: (141, 213, 4, 3)
1.8971 km: (116, 118, 10, 3)
1.9545 km: (39, 145, 10, 5)
1.9556 km: (1, 265, 10, 3)
1.985 km: (62, 280, 8, 3)
1.9904 km: (68, 158, 2, 2)
2.0196 km: (15, 78, 6, 4)
2.0266 km: (175, 253, 5, 4)
2.0311 km: (95, 123, 11, 2)
2.056 km: (110, 265, 10, 2)
2.0574 km: (62, 168, 8, 4)
2.0609 km: (100, 111, 9, 4)
2.0801 km: (13, 279, 12, 4)
2.1085 km: (168, 179, 8, 3)
2.1146 km: (116, 117, 10, 3)
2.1214 km: (174, 253, 5, 4)
2.136 km: (221, 294, 2, 3)
2.1526 km: (125, 271, 10, 3)
2.1541 km: (24, 156, 2, 3)
2.1638 km: (180, 199, 8, 2)
2.1684 km: (41, 42, 7, 3)
2.1753 km: (123, 145, 11, 4)
2.1827 km: (51, 215, 2, 2)
2.1866 km: (58, 119, 9, 3)
2.1872 km: (112, 196, 2, 2)
2.189 km: (160, 266, 10, 3)
2.263 km: (13, 225, 13, 2)
2.2681 km: (172, 282, 7, 4)
2.2903 km: (177, 239, 2, 3)
2.3033 km: (66, 85, 4, 3)
2.347 km: (144, 282, 7, 4)
2.357 km: (37, 301, 2, 3)
2.4342 km: (112, 181, 2, 3)
2.4648 km: (30, 190, 10, 3)
2.4689 km: (121, 261, 9, 3)
2.4798 km: (77, 93, 9, 4)
2.5531 km: (88, 256, 2, 2)
2.6761 km: (116, 132, 10, 4)
2.7335 km: (164, 247, 2, 4)
2.9623 km: (95, 224, 11, 4)
3.1017 km: (168, 214, 8, 4)
3.1713 km: (11, 94, 8, 6)
3.2088 km: (68, 256, 2, 3)
3.2349 km: (6, 46, 8, 4)
3.3108 km: (46, 53, 8, 4)
3.4683 km: (53, 214, 8, 4)
5.3929 km: (46, 50, 8, 8)
7.0938 km: (94, 282, 8, 7)